### ISSUE TITLE
About constants in env files

### ISSUE THREAD

**Issue by masakifukunishi** [uzura89/nomadable#1]
Is there something that shows the constants in the env file such as .env.example?

**Comment by uzura89** [comment]
Thanks for mentioning! I have added .env.example file. Also, I removed some of the irrelevant variables. 
https://github.com/uzura89/nomadable/commit/622af744cc661208e568efaea3cf9720e35f473c

I'm new to do the open source world so still learning stuff. 
If you experience any inconvenience, please raise issues here. Thanks!

**Comment by masakifukunishi** [comment]
Thanks for responding!

I defined only MAPBOX_ACCESS_TOKEN in the .env file.
But errors are still occurring.
`Unchecked runtime.lastError: Cannot find menu item with id convertPageContextMenu`

Are all constants in the .env file required to display the top page?

**Comment by uzura89** [comment]
Not all constants in the .env file are required. Actually, MAPBOX_ACCESS_TOKEN is enough to load the top page.
However, there are other steps needed to run the app. Sorry that it wasn't clear. 

I have added an installation guide to README file. So please read it and you should be able to run the app on your local machine.

**Comment by masakifukunishi** [comment]
Thank you for adding the README :)
I was able to view the top page.
I am not very familiar with MongoDB, is there something I can see the structure of the collection?

**Comment by uzura89** [comment]
Great! The data structure is defined in the "models" directory.

Sent via Superhuman ***@***.***>

**Comment by masakifukunishi** [comment]
Thanks! I have confirmed it.
Now that I've resolved the issue about the env file, I'll close this issue :)
